name: Build, Publish to Cloudflare Pages

on:
  push:
    branches:
      - main
      - dev
      - stage

env:
  NODE_VERSION: 24

jobs:
  deploy:
    name: Build and Publish
    runs-on: amd64
    container:
      image: node:24-bullseye
    permissions:
      contents: read
      deployments: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        run: |
          if command -v bun >/dev/null 2>&1; then
            echo "Bun already available: $(bun -v)"
          else
            curl -fsSL https://bun.sh/install | bash
          fi
          echo "$HOME/.bun/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: bun install

      - name: Determine environment and branch
        run: |
          case "$GITHUB_REF" in
            refs/heads/main)
              echo "INFISICAL_ENV=mainnet" >> $GITHUB_ENV
              echo "BRANCH=main" >> $GITHUB_ENV
              ;;
            refs/heads/dev)
              echo "INFISICAL_ENV=testnet" >> $GITHUB_ENV
              echo "BRANCH=dev" >> $GITHUB_ENV
              ;;
            refs/heads/stage)
              echo "INFISICAL_ENV=stage" >> $GITHUB_ENV
              echo "BRANCH=stage" >> $GITHUB_ENV
              ;;
            *)
              echo "Branch $GITHUB_REF_NAME not configured for deployment"
              exit 0
              ;;
          esac
          echo "Resolved BRANCH: $BRANCH"
          echo "Resolved INFISICAL_ENV: $INFISICAL_ENV"

      - name: Install Infisical CLI
        run: |
          curl -1sLf 'https://artifacts-cli.infisical.com/setup.deb.sh' | bash
          apt-get update && apt-get install -y infisical


      - name: Build project
        run: |
          echo "Building with INFISICAL_ENV=$INFISICAL_ENV"
          infisical run --projectId=${{ secrets.INFISICAL_PROJECT_ID }} --env="$INFISICAL_ENV" --token=${{ secrets.INFISICAL_TOKEN }} --domain=${{ secrets.INFISICAL_API_URL }} -- bun run build

      - name: Install Wrangler
        run: npm install -g wrangler@3
        
      - name: Deploy to Cloudflare Pages
        run: |
          infisical run \
            --projectId=${{ secrets.INFISICAL_CF_PROJECT_ID }} \
            --env="$INFISICAL_ENV" \
            --token=${{ secrets.INFISICAL_CF_TOKEN }} \
            --domain=${{ secrets.INFISICAL_API_URL }} \
            -- bash -c '
              set -e

              wrangler pages deploy dist \
                --project-name "$CF_PAGES_PROJECT_NAME" \
                --branch "$BRANCH"
            '
