# woodpecker.yml
# Build Vite app and deploy to Cloudflare Pages using secrets

clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      depth: 0

########### Testnet Pipeline ###########
steps:
  # Step 1: Build the Vite app (runs on all branches)
  - name: build
    image: node:22-bullseye
    environment:
      INFISICAL_API_URL:
        from_secret: INFISICAL_API_URL
      INFISICAL_TOKEN:
        from_secret: INFISICAL_TOKEN
      INFISICAL_PROJECT_ID:
        from_secret: INFISICAL_PROJECT_ID
      INFISICAL_ENV:
        from_secret: TESTNET_INFISICAL_ENV
      INFISICAL_FOLDER:
        from_secret: INFISICAL_FOLDER
    when:
      event: manual
      branch: [dev, testnet]
    commands:
      - curl -1sLf 'https://artifacts-cli.infisical.com/setup.deb.sh' | bash
      - apt-get update && apt-get install -y python3 make g++ pkg-config libudev-dev infisical
      - corepack enable
      - yarn set version 4.5.1
      - yarn install
      - infisical run --projectId $INFISICAL_PROJECT_ID --env $INFISICAL_ENV --path $INFISICAL_FOLDER --token $INFISICAL_TOKEN --domain $INFISICAL_API_URL -- yarn build


  # Step 2: Deploy to Cloudflare Pages (runs only when manually triggered)
  - name: deploy
    image: node:22-bullseye
    environment:
      CF_API_TOKEN:
        from_secret: cf_api_token
      CF_ACCOUNT_ID:
        from_secret: cf_account_id
      CF_PROJECT_NAME:
        from_secret: testnet_cf_project_name
      BRANCH:
        from_secret: testnet_cf_branch
    when:
      event: manual
      branch: [dev, testnet]
    commands:
      - corepack enable
      - yarn dlx wrangler@latest pages publish dist --project-name $CF_PROJECT_NAME --branch $BRANCH

  ########### Mainnet Pipeline ###########
  - name: build
    image: node:22-bullseye
    environment:
      INFISICAL_API_URL:
        from_secret: INFISICAL_API_URL
      INFISICAL_TOKEN:
        from_secret: INFISICAL_TOKEN
      INFISICAL_PROJECT_ID:
        from_secret: INFISICAL_PROJECT_ID
      INFISICAL_ENV:
        from_secret: MAINNET_INFISICAL_ENV
      INFISICAL_FOLDER:
        from_secret: INFISICAL_FOLDER
    when:
      event: manual
      branch: [main, mainnet]
    commands:
      - curl -1sLf 'https://artifacts-cli.infisical.com/setup.deb.sh' | bash
      - apt-get update && apt-get install -y python3 make g++ pkg-config libudev-dev infisical
      - corepack enable
      - yarn set version 4.5.1
      - yarn install
      - infisical run --projectId $INFISICAL_PROJECT_ID --env $INFISICAL_ENV --path $INFISICAL_FOLDER --token $INFISICAL_TOKEN --domain $INFISICAL_API_URL -- yarn build

  # Step 2: Deploy to Cloudflare Pages (runs only when manually triggered)
  - name: deploy
    image: node:22-bullseye
    environment:
      CF_API_TOKEN:
        from_secret: cf_api_token
      CF_ACCOUNT_ID:
        from_secret: cf_account_id
      CF_PROJECT_NAME:
        from_secret: mainnet_cf_project_name
      BRANCH:
        from_secret: mainnet_cf_branch
    when:
      event: manual
      branch: [main, mainnet]
    commands:
      - corepack enable
      - yarn dlx wrangler@latest pages publish dist --project-name $CF_PROJECT_NAME --branch $BRANCH
